#Sprint 3, T04

##Nivell 1

###Execise 1 - Array

In [12]:
import numpy as np
a = np.array([20,30,8,6,9,21,64,18], dtype = int)
x = a.ndim
y = a.size
z = a.dtype
if x != 1:
    print("Error, array has more than 1 dimension")
else:
    print("Array has 1 dimension, number of elements is",y, "and the data type is",z)

Array has 1 dimension, number of elements is 8 and the data type is int64


###Execise 2 - Function to generate random NxN

In [25]:
import random
n = 3
b = np.random.randint(100, size = (n,n))
print("Random set of 2D array NxN:")
print(b)

Random set of 2D array NxN:
[[57  1 50]
 [59 95 43]
 [ 9 68 93]]


###Execise 3 - Function to calculate total value in columns and rows

In [27]:
a = np.array([(20,30,8,6,9,21,64,18), (25,15,80,61,17,20,55,11)], dtype = int)
x = a.sum(axis=0)
y = a.sum(axis=1)
print("Total value of each column is", x)
print("Total value of each row is", y)

Total value of each column is [ 45  45  88  67  26  41 119  29]
Total value of each row is [176 284]


###Execise 4 - Correlation

In [31]:
a = np.arange(10, 20)
b = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
r = np.corrcoef(a, b)
x = r[0][1]
print("Pearson correlation coefficient is", x)
print("That means the correlation in strong positive")

Pearson correlation coefficient is 0.7586402890911867
That means the correlation in strong positive
