#Sprint 3, T04

##Nivell 1

###Execise 1 - Array

In [8]:
import numpy as np
a = np.array([10,8,10,8,8,4,64,18], dtype = int)
x = a.ndim
y = a.size
z = a.dtype
if x != 1:
    print("Error, array has more than 1 dimension")
else:
    print("Array has 1 dimension, number of elements is",y, "and the data type is",z)

Array has 1 dimension, number of elements is 8 and the data type is int64


####Statistical analysis

In [10]:
#mean, max, median, min, std
b = a.mean()
c = a.max(axis=0)
d = a.min()
e = np.median(a)
f = np.std(a)
print("The mean is", b)
print("The max value is", c)
print("The min value is", d)
print("The median value is", e)
print("The standard deviation is", f)

The mean is 16.25
The max value is 64
The min value is 4
The median value is 9.0
The standard deviation is 18.423829677892705


###Execise 2 - Function to generate random NxN

In [14]:
#to generate num between 0 and 100 - 100 iclusive so the range is up to 101
import random
n = 3
b = np.random.randint(101, size = (n,n))
print("Random set of 2D array NxN:")
print(b)

Random set of 2D array NxN:
[[ 19  38  71]
 [100  43  30]
 [ 79  81  75]]


###Execise 3 - Function to calculate total value in columns and rows

In [15]:
a = np.array([(20,30,8,6,9,21,64,18), (25,15,80,61,17,20,55,11)], dtype = int)
x = a.sum(axis=0)
y = a.sum(axis=1)
print("Total value of each column is", x)
print("Total value of each row is", y)

Total value of each column is [ 45  45  88  67  26  41 119  29]
Total value of each row is [176 284]


###Execise 4 - Correlation

####The Pearson correlation coefficient measures the linear association between variables. Its value can be interpreted like so:

* +1 - Complete positive correlation
* +0.8 - Strong positive correlation
* +0.6 - Moderate positive correlation
* 0 - no correlation whatsoever
* -0.6 - Moderate negative correlation
* -0.8 - Strong negative correlation
* -1 - Complete negative correlation

####How to calculate correlation manually: https://www.statisticshowto.com/probability-and-statistics/correlation-coefficient-formula/

In [44]:
a = np.arange(10, 20)
b = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

#sum a
sumA = a.sum()
#sum b
sumB = b.sum()
#sum a*b
sumAB = np.multiply(a,b)
sumAB = sumAB.sum()
#sum a square root
sumA2 = a**2
sumA2 = sumA2.sum()
#sum b square root
sumB2 = b**2
sumB2 = sumB2.sum()

x = (10*sumAB) - (sumA * sumB)
y = np.sqrt(((10*sumA2)-(sumA**2))*((10*sumB2)-(sumB**2)))
result = x / y
result

0.7586402890911869

#Correlation coefficient is 0.75

In [45]:
#to check if it's correct
r = np.corrcoef(a, b)
x = r[0][1]
print("Pearson correlation coefficient is", x)
print("That means the correlation in moderate positive")

Pearson correlation coefficient is 0.7586402890911867
That means the correlation in moderate positive
